### PR TITLE
Add devcontainer

### PR DESCRIPTION
**Pull request by sigma-andex**

### CODE REVIEW

**Review by EricLBuehler — CHANGES_REQUESTED** [review]
Looks good, except for 2 small things:
- Currently trying to merge to the custom CUDA kernel branch which does not need this
- Installs PyTorch 2.1.2, should install PyTorch 2.1.0

**Comment by sigma-andex** [comment]
In theory 2.1.2 should work right? If they use proper semantic versioning. We could still use the devcontainer in the cudarc branch to have the same setup and make compilation of cuda kernels easy.

**Comment by EricLBuehler** [comment]
True. My only concern is that tch-rs says 2.1.0, but this should work.

**Comment by EricLBuehler** [comment]
Thanks!

**Pull request merged**
