### PR TITLE
Add support for the Gemma 2 model

### PR DESCRIPTION
**Pull request by EricLBuehler**
Refs #79

### CODE REVIEW

**Comment by EricLBuehler** [comment]
@guoqingbao the model runs but seems to give garbage output. Do you see anything which stands out?

**Comment by guoqingbao** [comment]
> @guoqingbao the model runs but seems to give garbage output. Do you see anything which stands out?

Perhaps there is a need for 'attn_logit_softcapping' if 'final_logit_softcapping' is used.

**Comment by guoqingbao** [comment]
I found the recent update #83 overwritten previous bug fixes including #80 @EricLBuehler

**Comment by guoqingbao** [comment]
> > @guoqingbao the model runs but seems to give garbage output. Do you see anything which stands out?
> 
> Perhaps there is a need for 'attn_logit_softcapping' if 'final_logit_softcapping' is used.

I have submitted a PR #86  to resolve the issue where both 'attn_logit_softcapping' and 'final_logit_softcapping' are necessary for gemma-2 inference. The corresponding PA kernel has also been revised. I'm curious why this isn't supported in vLLM. Google only mentioned that softcapping is beneficial for training.

**Comment by EricLBuehler** [comment]
@guoqingbao sounds good, I'll close this PR!

**Pull request closed without merging**
